### ISSUE TITLE
dumdohd support for SO_REUSEPORT

### ISSUE THREAD

**Issue by pspacek** [DNS-OARC/dumdumd#31]
Could you pretty please add support for SO_REUSEPORT to make dumdohd useful for multi-core systems?

Thank you!

**Comment by jelu** [comment]
Uhm, it already does that:
```
        listener = evconnlistener_new_bind(
            evbase, acceptcb, app_ctx, LEV_OPT_CLOSE_ON_FREE | LEV_OPT_REUSEABLE,
            listen_backlog, rp->ai_addr, (int)rp->ai_addrlen);
```
```
LEV_OPT_REUSEABLE

    By default on some platforms, once a listener socket is closed, no other socket can bind to the same port until a while has passed. Setting this option makes Libevent mark the socket as reusable, so that once it is closed, another socket can be opened to listen on the same port.
```

Not working?

**Comment by pspacek** [comment]
I think that's something else - sounds like description of REUSEADDR to me. Reproducer: Try to run the command **twice** in parallel on the same port. It will fail the second time.

**Comment by jelu** [comment]
Yes and no, they actually refer to multiple servers: https://libevent.org/doc/listener_8h.html#af417f499a89518d16eb3be4098e504c7
